### ISSUE TITLE
Changing the language or appearance crashes the app in release build

### ISSUE THREAD

**Issue by talha-irshad-kodexo** [kanzitelli/expo-starter#18]
Hi, I was using your code as a boilerplate for my app and faced this issue in which changing the language or appearance crashes the app in release build. The app works fine while development in expo or expo go but after creating a release build, it crashes the app and the mobx store gets emptied too. It seems like reloadAsync used is not functioning properly. I was wondering if you have faced this issue and if you did, how did you resolved it or is there any alternative to reloadAsync that you used because I tried everything but got no luck. Thanks

**Comment by kanzitelli** [comment]
Hey @talha-irshad-kodexo! That's weird because `reloadAsync` is a function from `expo-updates`. Have you tried looking in `expo-updates` issues?

You can also try using [react-native-restart](https://github.com/avishayil/react-native-restart) but it requires adding native part. For example, you can check [rn-starter](https://github.com/kanzitelli/rn-starter), [here](https://github.com/kanzitelli/rn-starter/blob/main/src/stores/ui.ts#L19) and [here](https://github.com/kanzitelli/rn-starter/blob/main/src/utils/help.ts#L5). 

Let me know how it goes!

**Comment by talha-irshad-kodexo** [comment]
Hi, It turned out to be my fault, I added another language and changed the languageFromInternalToUI function and added another ternary operator for checking the third language and that messed up the project. I then converted the ternary to if else and it works well now.
