### ISSUE TITLE
Newbie questions (mmkv, auth)

### ISSUE THREAD

**Issue by LansPeti** [kanzitelli/expo-starter#42]
Hey @kanzitelli,

my goal is to create a simple note taking app that saves the data on the users device, but the user can also log in and share it on a wall.
I also want to add a meditation feature in the app to make it more unique (I would use reanimated and mmkv).
My main goal with the app is to put it in my portfolio, that I can use to find a job finally. 

So thats about the me, but the details:
1. I see that the MMKV part is commented. If I want to use it for the notes, should I just uncomment those parts and its done?
2. Should I use MMKV storages for both the auth and notes so I mean, when should I use it and when not?
3. If I wanted to use a regular expo-google-auth combination, I just used this article: https://docs.expo.dev/guides/google-authentication/ (expo-auth-session, expo-crypto, expo-web-browser)
Now I'm a bit lost on how should I do that. Could you give me some instructions?

Thanks in ordnung for your answer!

**Comment by kanzitelli** [comment]
Hi @LansPeti!

That sounds like a good idea for a portfolio project 👍 They also like it to be open sourced, so consider doing that also.
You can take a look at this app I've built long time ago - https://github.com/starters-dev/notes-expo-app, maybe will be a good start point.

1. MMKV part is commented because it's not preinstalled in Expo App so you need to use AsyncStorage. However, if you will use expo prebuild feature, you will be able to use MMKV, as an app will be installed on your machine/phone. Which means you can use any native module.
2. You can use MMKV for any purpose. It's amazing lib.
3. This question I won't be able to answer as I've never done it on my end.

Hope the reply will help you in a way!

**Comment by kanzitelli** [comment]
I am closing the issue. If you have any updates, feel free to open it.
